development:
  adapter: postgresql
  encoding: unicode
  database: Tester_development
  pool: 5
  host: localhost
  username: gowtham1
  password: Simform@123

test:
  adapter: postgresql
  encoding: unicode
  database: Tester_test
  pool: 5
  host: localhost
  username: gowtham1
  password: Simform@123

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %> 